c  -*- Fortran -*-
      write(*,*) '****************************************************************************'
      write(*,*) '****************************************************************************'
      write(*,*) '                                                       '
      write(*,*) '****************************************************************************'
      write(*,*) '****************************************************************************'
      write(*,*) '***                                                                      ***'
      write(*,*) '***             '//achar(27)//'[1;31m********************************************'//achar(27)//'[0m'//'             ***'
      write(*,*) '***             '//achar(27)//'[1;31m*         XX-MiNNLOPS Beta Version 0.0     *'//achar(27)//'[0m'//'             ***'
      write(*,*) '***             '//achar(27)//'[1;31m********************************************'//achar(27)//'[0m'//'             ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m If you use this program for scientific work, please cite: '//achar(27)//'[0m'//'          ***'
      write(*,*) '*** '//achar(27)//'[1;31m Peter Pan, Mario, Luigi Brothers, Dirk Nowitzki (arXiv:1337.1337)'//achar(27)//'[0m'//'   ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the MiNNLOPS method (original and extension to 2->2):'//achar(27)//'[0m'//'           ***'
      write(*,*) '*** '//achar(27)//'[1;31m P. Monni, P. Nason, E. Re, M. Wiesemann, G. Zanderighi'//achar(27)//'[0m'//'              ***'
      write(*,*) '*** '//achar(27)//'[1;31m (arXiv:1908.06987)                                    '//achar(27)//'[0m'//'              ***'
      write(*,*) '*** '//achar(27)//'[1;31m P. Monni, E. Re, M. Wiesemann (arXiv:2006.04133)'//achar(27)//'[0m'//'                    ***'
      write(*,*) '*** '//achar(27)//'[1;31m D. Lombardi, M. Wiesemann, G. Zanderighi (arXiv:2010.10478)'//achar(27)//'[0m'//'         ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m For the XX-loop amplitudes): '//achar(27)//'[0m'//'                                       ***'
      write(*,*) '*** '//achar(27)//'[1;31m Donald Duck, Optimus Prime, Luca Doncic (arXiv:4.8.15.16.23.42)'//achar(27)//'[0m'//'     ***'
      write(*,*) '***                                                                      ***'
      write(*,*) '*** '//achar(27)//'[1;31m You are also encouraged to cite HOPPET for PDF evolution   '//achar(27)//'[0m'//'         ***'
      write(*,*) '*** '//achar(27)//'[1;31m G.P. Salam & J. Rojo, CPC 180(2009)120 (arXiv:0804.3755)'//achar(27)//'[0m'//'            ***'
      write(*,*) '***                                                                      ***'
